CREATE DATABASE QuanLyBanHang
on(
	name = qlbd_data,
	filename = "E:\TaiLieuHocTap\HOU\CongNgheThongTin\Programing\LTW_NC\ChuyenDe_QuanLyBanHang\qlbd_data.mdf" 
);
USE QuanLyBanHang

CREATE TABLE tbl_taikhoan
(
	sMaTK		NVARCHAR(100) NOT NULL,
	FK_sMaNV	NVARCHAR(100) NOT NULL,
	sTenTK		NVARCHAR(100) NOT NULL,
	sMatKhau	NVARCHAR(100) NOT NULL,
	FK_iMaQuyen	int NOT NULL,
	CONSTRAINT PK_sMaTK PRIMARY KEY(sMaTK)
)

CREATE TABLE tbl_quyen
(
	iMaQuyen	int identity NOT NULL,
	sTenQuyen	NVARCHAR(100) NOT NULL,
	CONSTRAINT PK_iMaQuyen PRIMARY KEY(iMaQuyen)
)



CREATE TABLE tbl_nhanvien
(
	sMaNV		NVARCHAR(100) NOT NULL,
	sTenNV		NVARCHAR(50) NOT NULL,
	sNgaySinh	NVARCHAR(50) NOT NULL,
	sGioiTinh	NVARCHAR(100) NOT NULL,
	sDiaChi		NVARCHAR(255) NULL,
	sSDT		NVARCHAR(15) NULL,
	FK_iMaCN	int NOT NULL,
	CONSTRAINT PK_sMaNV PRIMARY KEY(sMaNV)
)

CREATE TABLE tbl_khachhang
(
	sMaKH		NVARCHAR(100) NOT NULL,
	sTenKH		NVARCHAR(50) NULL,
	sLoaiKH		NVARCHAR(50) NULL,
	sSDT		NVARCHAR(15) NULL,
	sGioiTinh	NVARCHAR(15) NULL,
	CONSTRAINT PK_sMaKH PRIMARY KEY(sMaKH)
)



CREATE TABLE tbl_loaiSP
(
	sLoaiSP		NVARCHAR(100) NOT NULL,
	sTenLoaiSP	NVARCHAR(255) NOT NULL,
	CONSTRAINT PK_sLoaiSP PRIMARY KEY(sLoaiSP)
)

CREATE TABLE tbl_chinhanh
(
	iMaCN		int identity NOT NULL,
	sTenCN		NVARCHAR(255) NOT NULL,
	sDiaChiChiNhanh NVARCHAR(255),
	CONSTRAINT PK_iMaCN PRIMARY KEY(iMaCN)
)

CREATE TABLE tbl_sanpham
(
	sMaSP			NVARCHAR(255) NOT NULL,
	sTensp			NVARCHAR(255) NOT NULL,
	iSoLuong		int NOT NULL,
	fDonGia			float NOT NULL,
	sTrangThai		NVARCHAR(255) NOT NULL,
	FK_sMaLoaiSP	NVARCHAR(100) NOT NULL,
	FK_sMaNhaCC		NVARCHAR(100) NULL,
	FK_sNguoiDangSP	NVARCHAR(100) NULL,
	sNgayDangSp		NVARCHAR(30) NULL,
	sMoTa			NVARCHAR(255) NULL,
	sXuatSu			NVARCHAR(255) NULL,
	FK_iMaCN		int NOT NULL,
	CONSTRAINT PK_sMaSP PRIMARY KEY(sMaSP)
)

CREATE TABLE tbl_anh
(
	sMaAnh		int identity NOT NULL,
	sLinkAnh	NVARCHAR(255) NOT NULL,
	sGhiChu		NVARCHAR(255) NULL,
	FK_sMaSP	NVARCHAR(255) NOT NULL,
	CONSTRAINT PK_sMaAnh PRIMARY KEY(sMaAnh)
)




CREATE TABLE tbl_nhacungcap
(
	sMaNhaCC	NVARCHAR(100) NOT NULL,
	sTenNhaCC	NVARCHAR(50) NOT NULL,
	sDiaChi		NVARCHAR(255) NULL,
	sDienThoai	NVARCHAR(50) NULL,
	sGhiChu		NVARCHAR(255) NULL,
	CONSTRAINT PK_sMaNhaCC PRIMARY KEY(sMaNhaCC)
)

CREATE TABLE tbl_phieunhap
(
	sMaPN			NVARCHAR(100) NOT NULL,
	sThoiGian_Nhap	NVARCHAR(50) NOT NULL,
	sGhiChu			NVARCHAR(255) NULL,
	FK_sNguoiLap	NVARCHAR(100) NULL,
	FK_iMaCN		int NOT NULL,
	FK_sMaNCC		NVARCHAR(100) NOT NULL,
	CONSTRAINT PK_sMaPN PRIMARY KEY(sMaPN)
)


CREATE TABLE tbl_chitietphieunhap
(
	FK_MaSP			NVARCHAR(255) NOT NULL,
	FK_MaPN			NVARCHAR(100) NOT NULL,
	iSoLuongN		int NOT NULL,
	fDonGiaN		float NOT NULL,
	fTongTien		float NOT NULL,
	CONSTRAINT PK_FK_MaSP_FK_MaPN PRIMARY KEY (FK_MaSP,FK_MaPN)
)


CREATE TABLE tbl_hoadon
(
	sMaHD			NVARCHAR(100) NOT NULL,
	sThoiGian_Lap	NVARCHAR(50) NOT NULL,
	FK_sMaKH		NVARCHAR(100) NOT NULL,
	FK_sNguoiLapHD	NVARCHAR(100) NOT NULL,
	FK_iMaCN		int NOT NULL,
	CONSTRAINT PK_sMaHD PRIMARY KEY(sMaHD)
)



CREATE TABLE tbl_chitiethoadon
(
	FK_MaHD			NVARCHAR(100) NOT NULL,
	FK_MaSP			NVARCHAR(255) NOT NULL,
	iSoLuongM		int NOT NULL,
	fDonGiaM		float NOT NULL,
	fTongTienM		float NOT NULL,
	CONSTRAINT PK_FK_MaHD_FK_MaSP PRIMARY KEY (FK_MaHD,FK_MaSP)
)

ALTER TABLE tbl_nhanvien ADD CONSTRAINT FK_NV_CN FOREIGN KEY(FK_iMaCN) REFERENCES tbl_chinhanh(iMaCN);

ALTER TABLE tbl_phieunhap ADD CONSTRAINT FK_PN_CN FOREIGN KEY(FK_iMaCN) REFERENCES tbl_chinhanh(iMaCN);

ALTER TABLE tbl_phieunhap ADD CONSTRAINT FK_PN_NCC FOREIGN KEY(FK_sMaNCC) REFERENCES tbl_nhacungcap(sMaNhaCC);

ALTER TABLE tbl_sanpham ADD CONSTRAINT FK_SP_CN FOREIGN KEY(FK_iMaCN) REFERENCES tbl_chinhanh(iMaCN);

ALTER TABLE tbl_sanpham ADD CONSTRAINT FK_sMaLoaiSP FOREIGN KEY(FK_sMaLoaiSP) REFERENCES tbl_loaiSP(sLoaiSP);

ALTER TABLE tbl_sanpham ADD CONSTRAINT FK_sNguoiDangSP FOREIGN KEY(FK_sNguoiDangSP) REFERENCES tbl_nhanvien(sMaNV);

ALTER TABLE tbl_sanpham ADD CONSTRAINT FK_sMaNhaCC FOREIGN KEY(FK_sMaNhaCC) REFERENCES tbl_nhacungcap(sMaNhaCC);

ALTER TABLE tbl_hoadon ADD CONSTRAINT FK_HD_CN FOREIGN KEY(FK_iMaCN) REFERENCES tbl_chinhanh(iMaCN);

ALTER TABLE tbl_hoadon ADD CONSTRAINT FK_sNguoiLapHDs FOREIGN KEY(FK_sNguoiLapHD) REFERENCES tbl_nhanvien(sMaNV);

ALTER TABLE tbl_hoadon ADD CONSTRAINT FK_sMaKH FOREIGN KEY(FK_sMaKH) REFERENCES tbl_khachhang(sMaKH);

ALTER TABLE tbl_chitietphieunhap ADD CONSTRAINT FK_PN_MaSP FOREIGN KEY(FK_MaSP) REFERENCES tbl_sanpham(sMaSP);

ALTER TABLE tbl_chitietphieunhap ADD CONSTRAINT FK_PN_MaPN FOREIGN KEY(FK_MaPN) REFERENCES tbl_phieunhap(sMaPN);

ALTER TABLE tbl_chitiethoadon ADD CONSTRAINT FK_CT_MaHD FOREIGN KEY(FK_MaHD) REFERENCES tbl_hoadon(sMaHD);

ALTER TABLE tbl_chitiethoadon ADD CONSTRAINT FK_CT_MaSP FOREIGN KEY(FK_MaSP) REFERENCES tbl_sanpham(sMaSP);

ALTER TABLE tbl_taikhoan ADD CONSTRAINT FK_iMaQuyen FOREIGN KEY(FK_iMaQuyen) REFERENCES tbl_quyen(iMaQuyen);

ALTER TABLE tbl_taikhoan ADD CONSTRAINT FK_sMaNV FOREIGN KEY(FK_sMaNV) REFERENCES tbl_nhanvien(sMaNV);

ALTER TABLE tbl_anh ADD CONSTRAINT FK_sMaSP FOREIGN KEY(FK_sMaSP) REFERENCES tbl_sanpham(sMaSP);

ALTER TABLE tbl_nhanvien ADD CONSTRAINT FK_iMaCN FOREIGN KEY(FK_iMaCN) REFERENCES tbl_chinhanh(iMaCN);